htl_spendenportal:
    resource: "@HtlSpendenportalBundle/Resources/config/routing.xml"
    prefix:   /

backend_admin:
    resource: "@BackendAdminBundle/Controller/"
    type: annotation
    prefix:   /backend/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"