<?php

namespace Backend\AdminBundle\Repository;

/**
 * DonatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonatorRepository extends \Doctrine\ORM\EntityRepository
{
}
