<?php

namespace Backend\AdminBundle\Repository;

/**
 * FollowerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowerRepository extends \Doctrine\ORM\EntityRepository
{
}
