<?php

namespace Htl\SpendenportalBundle\Repository;

/**
 * ProjectAmountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureRepository extends \Doctrine\ORM\EntityRepository
{
}
