<?php

namespace Htl\SpendenportalBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /*
     * public function findOneByIdJoinedToProjectamount($productId)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p.*, pa.* FROM AppBundle:Product p
            JOIN p.categorys pa
            WHERE p.id = pa.id'
            )->setParameter('id', $productId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
     */
}
