<?php

namespace Backend\AdminBundle\Repository;

/**
 * ReceiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiverRepository extends \Doctrine\ORM\EntityRepository
{
}
